# Generated by Django 3.2.7 on 2021-09-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('year', models.CharField(max_length=4)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=15)),
                ('dimensions', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=10)),
            ],
        ),
    ]
